### ISSUE TITLE
Adding matplotlib colormaps

### ISSUE THREAD

**Issue by sjaumann** [Gnuplotting/gnuplot-palettes#2]
Hi, 

Thanks for this great compilation!
I gathered the colormaps from matplotlib and brought it into the gnuplot format. However, I did not take the time to create the linestyles for the colormaps, except the viridis colormap. 

If you like, you can add these colormaps to the others. 

Best, 
Stefan

[matplotlib-colormaps.zip](https://github.com/Gnuplotting/gnuplot-palettes/files/452778/matplotlib-colormaps.zip)

**Comment by hagenw** [comment]
Thanks, it's now included. I updated all the line styles and reversed the order of the colormap to be consistent with all the other ones.

**Comment by hagenw** [comment]
I was wrong regarding the order and restored your original order.
I have also created a blog entry to mention that they are now included: http://www.gnuplotting.org/matplotlib-colormaps/
