### ISSUE TITLE
reference to kenneth moreland at sandia do not work anymore

### ISSUE THREAD

**Issue by xtforever** [Gnuplotting/gnuplot-palettes#7]
reference to kenneth moreland at sandia do not work anymore

I suggest using this link 
* https://www.kennethmoreland.com/color-maps/
to his paper

https://www.sandia.gov/~kmorel > causes 404

**Comment by hagenw** [comment]
Thanks for reporting, I fixed it in https://github.com/Gnuplotting/gnuplot-palettes/pull/8
